apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "test"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "test"
    spec:
      containers:
        - name: "test"
          image: "luan123.azurecr.io/test"
          ports:
          - containerPort: 3000