on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: luan123.azurecr.io
        username: ${{ secrets.acr_luan123_username }}
        password: ${{ secrets.acr_luan123_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/guestbook/php-redis" -f  "guestbook/php-redis/Dockerfile" -t luan123.azurecr.io/test:${{ github.sha }}
        docker push luan123.azurecr.io/test:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_test_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep test2e23 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace test2e23`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: test2e23
        container-registry-url: luan123.azurecr.io
        container-registry-username: ${{ secrets.acr_luan123_username }}
        container-registry-password: ${{ secrets.acr_luan123_password }}
        secret-name: testdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: test2e23
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          luan123.azurecr.io/test:${{ github.sha }}
        imagepullsecrets: |
          testdockerauth